---
kind: pipeline
name: default

steps:
  - name: build
    image: devopsworks/ansible-cloud
    pull: always
    shell: bash

    environment:
      GCE_CREDENTIALS:
        from_secret: gce_credentials
      GCE_SERVICE_ACCOUNT_EMAIL:
        from_secret: gce_service_account_email
      GCE_PROJECT_ID:
        from_secret: gce_project_id

    commands:
      # - workon 2.4
      # - molecule test
      # - workon 2.5
      # - molecule test
      # - workon 2.5
      # - molecule test
      - id
      - cat /etc/environment
      - ls /usr/libexec/virtualenv || true
      - workon 2.7
      - molecule test'
      # - bash -lc 'source /etc/bash_completion.d/virtualenvwrapper; workon 2.7; molecule test'
      # - molecule test
      # - workon 2.8
      # - molecule test

---
kind: secret
name: gce_credentials
data: q4XAR2o9o77AyF62JoUReXvJPeWZMv4DX2k9O0KcuBwVDosSOhUzMH2Bpa9fBm+ZG/sYB7rfoASTe/dKQzhRIsA7XZd8DXJOgY14sI+ZVBwl9oBY17rSg7LG/QFVYjXGB2czfXswAdHYMvARI2fyaHRU2/zmNQvao6zpRrZkAX7BU+hDpLMY48aDwwvG+g96zyUqykfz9WFlDZFJeAt09AJ/HLOK8WDHon5Nsicn9wMZWOXW1aF6Y214FzYEixJu/4JU1zN39RRobGn4+poIA1YWy29jVK+0SokMcXhBy87yndB/rZ+MeAFEEpWaVDUcN2GqbZKedt4NBzo2pEXK6x4jtZhViP9Nv+6uytoD371kC9fCyVV7YmuqmJvmBZIJO4pFHapOVg+/JASqNhtAEUddrvPFfkY+bZzXkmqescSlQh80e/FQgWtZ56Ir3BJ8yPIElS2zALl2aV52i6wfTEC1ZLyqUN7IJKcAVduPsA8Ks1byUzV7bTr7BbA2uAY+uwHSa38gIGO6SnqPfI26U+qeDv56NhqwRpiQz2UYV09HQmeHtKR9+g2PHqs9dWKH6wP7hk6FxotvcCE12ZA4u/xar45coIvBYVxKVTShsqIQYSj0W7B1ya9P2xLbmwM6etgHxVlS3m8fJ4UvAHRp5DKWW4D9DizQI5iYCsG4OImBok8VOn6pFY00Pt8v7ETO3VPRx2uqar/Me/I9BD+aXMQ9MRYORfApJb10QdvfQ1pAXGEmc4kAkgWKGuPsuay+Nf31D0SAIFhCdWCQe0OszWcshIeXeteCwKn9eoIkhFV9nH/0+4zx24e25KG2KXBbTKa5ccelapvXoA97S0bWk6nZ+9PHmV/1kDgt0MPybEkmt1PTnxQ1SlEi5GjkH69n+WINeBCkOxoN83ntewuemPNGeat3ap79AQ+8hkf75CLtB2zxtJrVCPMFPaJgSSnQnCKHh27xQFDcUE+9j6PoPI0yYFIZbvCNwIQ+ImQnuJ3V4DtA/vA/OspRtjsvSBPs2bNf2V9lYS+gt0iSb6ZC3mshX5O1/eFunkL51sQDqodK2uFWeiipwQuHFzfRptXnSJGzCFmhVZpI32jM40X0gpbKPyVIkqFNRSBIvHlRCbO/2kAcKSPR5Bf3FWh9FuxCd9A15X4abQnK72H3jZ6zaJbZ7FqPdRxECkxqRy8xpFD1ARHIF7h/WjWH/z7SjF4FtGSiMOo8oKRR3evIZWUfUnJ+1Jc5M7Snb7qe2uk2fF6kfXB8NLERYBbYbUlXOTyL5OqankjWJxQkQMeYemlVOM5ot77VyY9eeRfSIxFWmQXZSDf1rGmbeAAOvFdCy6755OSnC3jtSfVvcs/E2teX+9pNF4Nam/hmx0o3frZq9TjN2mOSYUBmv6B/m7mxWA1yLBvivUQjKSp78lr2G33+F+IO1E7gJyu5sMGoandQbbwwVr73x4Rdpq5cxmigceDKVDh5ajlMugjy3qciyMuy0znK7ULGMBQlrAxxUxW8PHe1dq7zNUO1oh16iqYcseYByrt25oXHk/RNdEgxK9s62BRKj2V78Zles73JC41s7gdrYbrGC4xVqhQp3x/2Er1Lcbz+09rVmc3J8EMckrpwb58aLJI2TbSv79MOItW0HEQqEEXBxwJTF7Q4EFBxz/whrMQ489GKtL36AKqEkZzh3wLet9SVzsdFy7F3BAA49jwC36SFEzTgEpIvsRnBZNGukR1k9rd0AT7pTyO5baEJNRCOfVipHO+Vt0uo6evnYn8whghU+8zUWyA8EDMoVPNZvTKaZF9HzxDQpbn2bsnKpWvEdRU5qI5B7psgLG8YBhcbJ5RneGCmHYQgKkTE0cfed06eVxaELSDh4DWlQe+veqpGoFwgXmIYgP9j7mXErdIpKXsD12GaxwiFyZGDQ2FFybP7ff/oJ9fJAy8J3VMCK4RPqRJkB4T8xng8q1FN8hHp/c10bd9fScSuzGUng+wL2P6PWNsXR3KvWmgW3QP8hZNjFLR8sVupe8IN9cNfUnJuTJJwDJEIgHT8aOVZa1ebizjygDuSLqPDjFvotXeRaTfh2tNShgPzUfQmoycAX4RZJuKCJ+weIOlMtmzn80PGYM2YbP8avnJBPMIqE8Ad0S2a5MZzK12yYfiRnV+7B0n8dj0geNuo88bBYkAaAB1ayfh86uPA1tLLfL3+ex0/Rro2DyArbcCM21WPs7OJoDmdzRsdNmIImXtGCey78iPWqiqz58oyeZg6C3wrtWgKU9Rb1pEA0AWf3h5WW4KnHa1FiOc6SuIEOGqXhkzh2zY82bgMw5e2O84ZIfNRkT1QGjs6fOkna6IKkKOz8wxijqi30UYBp2oLl1QAA+q9g5J6ea++Er3Bp/6U53ewgXBtPboZ78tcu+Hjih2/mGmbcqceRl18qxotSLYNnR9h86kpE2UFp+Q0VXTV5yhOIX5fyFK/5HdmNxXWcsiqaay1UzyQGsYwc4N+EcAr+moUVioOXsTaypcn4sFbHR2PCc2TmP5ONNERN18gOr2AVdpb3KobuvJda+5wEh+t4qIuhyhnet2wMOyBJL6K3VspiEiAhvXLfMHXP88+o1p0EnQm8zlmc1AkMyjfUh+ouxJx3CIb+KJ2S1kOb5w4N+wtx3WQiSshwA6eVQxWBzLdefPxfKgDq0TqpPbNjlLCfN/GFohHHkYjAmLyQ+WKAGfNevHjsBnjFBb/7vfzXLIxrQwlWHdXLnmgJY8ncJLzoFwezIsgmvuy9V8I1JfggNwFWxKSmPhCSSRsFTo0GCzsHZHJcvdYbIRiZtPuba1BEAxFvuMz2uiVHbn1SzaEb4758bi5bS9eog4zU6LSNfWxA/CpgqulD7N0OTxCtmh6/mPQ7r9Q26xjPqAcbfWEsBLR5MyGAXZN9NYOpJYq2bpCYjoa4TyRzXrcHIipdW+rG6wsUj8tC/rxLJ/De+sQdRGPDKL8qAsLpV+hwzZcEwAl0CRSBZm4oH5NdkFMMPw+n5IG9osdVe6goQpxbS8JxuxnKZOWsoG0URkJCbYhR+xrx05sIBZvO6MPYaRci2t2PpXTa5CvBXu9ICaIw6yUSrnaACjS1w==

---
kind: secret
name: gce_service_account_email
data: qTuMCmON2Dftrf0o2XkSp0UqgGf0+zkZPJdvvRhCcgx9yre5fojIcjBWR9ZXjvlqLzVtMqFOneS+yHLCTfHAxyV9KlklsKQKzlKk

---
kind: secret
name: gce_project_id
data: hcsJM/pa+YSQ9uNQmfOQ7qpk/JRJuw48H0QP7t6e21HJBhWaUtg7YenY
