---
kind: pipeline
name: default

steps:
  - name: build
    image: devopsworks/ansible-cloud
    pull: always
    shell: bash

    environment:
      GCE_CREDENTIALS:
        from_secret: gce_credentials
      GCE_SERVICE_ACCOUNT_EMAIL:
        from_secret: gce_service_account_email
      GCE_PROJECT_ID:
        from_secret: gce_project_id

    commands:
      # - workon 2.4
      # - molecule test
      # - workon 2.5
      # - molecule test
      # - workon 2.5
      # - molecule test
      - id
      - cat /etc/environment
      - ls /usr/libexec/virtualenv || true
      # - workon 2.7
      # - molecule test'
      # - bash -lc 'source /etc/bash_completion.d/virtualenvwrapper; workon 2.7; MOLECULE_DEBUG=1 molecule test -s gce'
      - bash -lc 'source /etc/bash_completion.d/virtualenvwrapper; workon 2.7; molecule test -s gce'
      # - molecule test
      # - workon 2.8
      # - molecule test

---
kind: secret
name: gce_credentials
data: UPq0SfycRyVGrsrXkHwFqqSY7LCwjzckmJTZMnFKzQicnnyWTwi/xiZz7uRF01UZ8xKNWMCBygkJ5Z9leG/vI1vHy52Z4WELvcL0VVPN5wV9TeuFGvoKxtar0SOdq0UKVCFYj8oGTLjkZjxSu8mmLGRGgpd3lb7oHtt6G/IETQ6seSBHPOmCrDylmqnviOv01ojmMcufkAPdEMhtleljPFvCiixyHzehd5Tz+8Rh69TkswAL/rgeQZJGXzTkFQCUFw03dcHaYMl8rrbJstwmP02gcdCOveOOAB4Q5d2hvJOu+pg3HBkP48lkoU2iN2kVWdWD1WOy56+KUd+j93vuoR4Az/0L4Uk7xpeq//oFOC/8SF3yvgbYgw5xaq0NjYxAoT+D/rgKfvMnw3JxS4FzDJkpPIwvXvyeV1Yle0LJtuLO9forFHbOe6NpOJIc0YtPtRQyptea6vqG1rgoUEhMkYTtfOSAmgCV//RQcPfLGbew5+Dmo3kkEgFqg+emQQSvbe7ZnmEm3KLK8SXrcLrYs3j6MWb/jQK23nnQpBDydyRiLMefI19VEraMLG4jgGqmw1Kl0ami1Dw0AZOlMxE6cTdXxTprLRqXMOT5st8MS3YAUo9eO+Z9jux+mUGn/l0D2kMQO/zMMq27WrVhMx8a2j5U8pUrzfilqVqEWzhfcj8X/GQ8Z9TWmDjDl5i2n2BVLAp3wxjF/fTWrpAfRgUI01O81QAzCAEprWP0v8ku1OghSQr3JuTqqg8bxsE7ZjbEGioCfUo0lMmMnQFSAdX6mcRFnGM3L7dFie1fdWqWnyiYGI5fLa95763zG4IDeoUw5GvNXTISPaNMjkLkgpJXlWM+sbnVaFLxOSl2XhPkmo8+jhzJCg9SknAIgtvDGe7deP826kJ+7GZby73V2nMBB2+e0Os+OG9dH1V4Bw574eRNcWyhlwUEMtqXZn/1/ZjpZnuiNc4C5b5DgYu/fSZtUJOts1cQI9+Y7j5L0iKCszfmvUHgXxyknyjEXKXyPGF5m+JIk/5lZZnFJPE3vU1zGuTGE6teNZ+L7slNZMbW1pD19LXuKA881Az1vKpS12x/6eBXSAfUqFphgU+bZp6MAxevw9ERhsXBEqLgceVUArjy6uJQd4XATUDIxfevt5eToHZNxJPJP1hWg+9DxCzGAYfsmMOF2nRsLj9sBseSLQ+vy+QgIkJ+cGsHufRjliZ/TEL9jBsXaRQUIa2Zv7aGMmVVYoZWJkoa/K4lOv06XV/q4JAYWdvu6UEWndJuEegTiazOuYESUx95X9CUMw/M642VKA+OgATiRFWOH4kyfXMo4MdEpUZI5OAVTWhvRuK2tktgtXtqcDRF77nqdlFU8fzYG9b2aJ0DS2xXTmYE/UNnct91LohwET5y6vXZGg5i0t9v5fFSpx3a5FzEjPxoA9mBlsQQCVdWsdfsT9pU3i34kIt5a+zTFFjnpuPr6ArQO22W6iCH/7dEQ6MRvChPbmF4tZMg5wDAYjYLHtduArXgIkciK6AvNQZU24Vh6benD+H8Xn9s/f0S7u+HPA1JcrrFSHpLqeCuUrABZK8qeX9nqmZaIGE0/e/SsKVS9zvrGmOsfd+p8V6VeuO6RtFTTMguAp7lfxgb1SGhFftB0wX5c4NKIRzUkI9Hkmh6lPvtKDKy4hsAVil8yQMmlF26J4c/Ogwqx8tWv3euJwh+etwXDE1Ve0tXs9BMNEA8lZb0aBA3SrDj6mz6XyDasMExVw9ST/+NQkhWkz4HGRobXqUGlvQe0Wy4fwEQ8bevLdzkO/aimPp2M2BfX1oTl8K083DB6q283jUcNaT36P0QMvuAVd/2jZkAoMuHSBdijk62ZAcVZPw6DqKlp4FvfCXcq1mdzmMjgWaA7xkBLlPo1NrB5ByxhHX3a+cZUR9BHcUnT24PMO8C/dTXaUE1gLw46wE8SfNBRIhCWUMUWglZQ/3bDZ/QqYCw+s7yqB0KR3O9eJ4p/cMDStCRUHYz80U3Q2CUZ/YZHsjuo4gPWQjpIsC06IxYaGrPIpTohVyyv8307z28YC+FrqIuqLpKFXGkQYvoipzYWq4sgQG20NoHlBxNKdqLeYyFwTXH1aPL4fN2/VuR6vj61UNgsY7q3CFzh5Jm5gHaYg3+/95ZxgoyiYh91ZaIKn2E8poShX8zvP9vKwf0aIdbNbajp6WkEVINw6SEJFRoc30MOHpJGdL4f4ZNBkZniSResWEDF30Om7S49CUF2S3sNZU2ZW4sy/0/vkZE1f+CmK1vhvlnB8Npbzx1ljvVnKE/uJ/Vzyl96j3s/vQcqquPg1WXkma+V+yCnTnpOomjdKx8nd+Ph1w0p+5Tjb+dl3D3rsM1i6F5sBcAb46++u3eW8ULZITaDC4a4DyUVt73HPIn106W2KT+Dl7+sgs+J1Kpanpt/3iS50r21jlhnWG7r8pHn18SJrXssgsH5HZV+1JEGD+HB8nxUcYooXmSF7Okxs51EPIUwDn1xR736jJeT4PTWUNtltp09E0ZEcpJ6SCXGeGXZFVfKuj4tNKdTxFue/jLHXa/8RQXA6ZWzbgoO8Kbe6DYT5AIbsBw7Qo7+RhcLpdms0KOZlC2earJsWf8AykHzlQCnwZoh8PkJ+WXnLZ/EMcV0w5i7djcvbaz0wxKzxYYzxSHFtiGt0rPyWbnWEjmxXxPJ7dFNVkP+9Uwb02tIdYf6ZH8Cos6YZGWBzXPOlmjmQ9wVAtCaXUR5KmYhLwkYbHzvZ+a1QnDngF8EAG16ve8KNsGi1y7q8aypHm4ZvKqTOT//tQ8q+V5KrmayxVFOZ6MExEIiNUPBfeLqHv3NJuzWCQgHZm6TDMDbllfJYTVRfso17NI+I8nnXMGBvluldRqOPY00vFfsvRdU3lbsEeLWwM7YrosonsfcLPb9fmEenNjZzCUIs7vinR5LDULUe9BkMRBhLCASU795h0hNNXgB7NJFKiCySmtPS8MYDjL5pcxlv/BdCGBFvbFnGf2CkKyj2TFOYPL8/u7yxqu0cCElPcmXVYRUGoC6Ppc0wEHEovX+fL6qsR5Mkbbz08NCvldbQFmp5H9KN4LAHHmcuQpXmY1tIVsBoftEjOf3fBMjdHNlNKqFhn6

---
kind: secret
name: gce_service_account_email
data: qTuMCmON2Dftrf0o2XkSp0UqgGf0+zkZPJdvvRhCcgx9yre5fojIcjBWR9ZXjvlqLzVtMqFOneS+yHLCTfHAxyV9KlklsKQKzlKk

---
kind: secret
name: gce_project_id
data: hcsJM/pa+YSQ9uNQmfOQ7qpk/JRJuw48H0QP7t6e21HJBhWaUtg7YenY
