---
language: python

env:
  - ROLE=$(echo $TRAVIS_REPO_SLUG | cut -f2 -d'/')

virtualenv:
  system_site_packages: true

before_install: true

install: true

script:
  - molecule test

notifications:
  slack:
    secure: f4s+CrjKmv58411G0QNkR5cro7MkzlIxAuujYovn/wA59LSvKNF/aK+wwrBya1IQZfH80CmcHZGKOKBVM7dDpnsEMkH5U/9Fu3NO1M8YqPcSQWSXvkEdvbkUgWoXbkUOWqxsbbe5SiBnbYDj40Z6zR5oWe/j79QmNb5Hj9UWDws=
