---
- name: Installs nginx
  apt:
    pkg: nginx-full
    state: latest  # noqa 403
    update_cache: yes
  register: __nginx_just_installed

- name: Writes nginx.conf
  template:
    src: nginx.j2
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Restart nginx

- name: Removes nginx default server link
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart nginx

- name: Removes nginx default server
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  notify: Restart nginx

- name: Writes nginx.conf
  template:
    src: nginx.j2
    dest: "/etc/nginx/nginx.conf"
  notify:
    - Reload nginx

- name: Replaces logrotate entry
  template:
    src: logrotate_nginx.j2
    dest: /etc/logrotate.d/nginx
    mode: 0644
