---
dependency:
  name: galaxy
driver:
  name: gce
lint:
  name: yamllint
platforms:
  - name: ansible-nginx-1604
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1604-xenial-v20190807
  - name: ansible-nginx-1804
    zone: europe-west1-b
    machine_type: f1-micro
    image: ubuntu-1804-bionic-v20190813a
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../playbook.yml

verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
  directory: ../tests
  lint:
    name: flake8
